### PR TITLE
Specify current limits in arm calculator is a stator current limit

### PR DESCRIPTION
**Pull request by HarryXChen3**
Make tooltip for current limit in the arm calculator page specifically say "Stator current limit".

### CODE REVIEW

**Comment by HarryXChen3** [comment]
Any thoughts on if this pr should be expanded to clarify current limits on other pages as well? If that's preferred I can probably also look through the linear mechanism, flywheel, etc.. pages (or is it known that all the current limits are stator current limits?)

**Comment by HarryXChen3** [comment]
Also was debating between updating the name of the field itself from "Current Limit" to "Stator Current Limit", but ultimately decided against it, but if doing that would make it even more clear what type of current limit it is, that's also a dead easy change.

**Comment by tervay** [comment]
Deploy preview for _recalc_ ready!

✅ Preview
https://recalc-hbt4xwpwz-tervay.vercel.app

Built with commit cf986d1fe43fa1e3adce245e5714ce73ed9689c9.
This pull request is being automatically deployed with [vercel-action](https://github.com/marketplace/actions/vercel-action)

**Comment by tervay** [comment]
> Also was debating between updating the name of the field itself from "Current Limit" to "Stator Current Limit", but ultimately decided against it, but if doing that would make it even more clear what type of current limit it is, that's also a dead easy change.

I think its fine as is. On my to-do list is support stator and supply limit inputs.

**Comment by tervay** [comment]
> Any thoughts on if this pr should be expanded to clarify current limits on other pages as well? If that's preferred I can probably also look through the linear mechanism, flywheel, etc.. pages (or is it known that all the current limits are stator current limits?)

All current limits currently are stator limits. I'll keep this PR as just arm calc but you're welcome to open other PRs to clarify other tooltips!

**Pull request merged**
